 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.19.0.6:4444/ (Press CTRL+C to quit)
127.0.0.1 - - [16/May/2025 09:30:34] "GET /hi HTTP/1.1" 200 -
127.0.0.1 - - [16/May/2025 09:31:04] "GET /hi HTTP/1.1" 200 -
127.0.0.1 - - [16/May/2025 09:31:34] "GET /hi HTTP/1.1" 200 -
127.0.0.1 - - [16/May/2025 09:32:04] "GET /hi HTTP/1.1" 200 -
127.0.0.1 - - [16/May/2025 09:32:34] "GET /hi HTTP/1.1" 200 -
222.201.187.50 - - [16/May/2025 09:32:56] "GET /start HTTP/1.1" 200 -
127.0.0.1 - - [16/May/2025 09:33:05] "GET /hi HTTP/1.1" 200 -
Exception on /conf/structure [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "gl_peer.py", line 86, in route_conf_s
    with open (filename, 'w') as fw:
FileNotFoundError: [Errno 2] No such file or directory: '/home/qianguo/EdgeScheduler/Worker/dml_file/conf/1/1_n1_structure.conf'
222.201.187.50 - - [16/May/2025 09:33:20] "[35m[1mPOST /conf/structure HTTP/1.1[0m" 500 -
Exception on /conf/dataset [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "gl_peer.py", line 73, in route_conf_d
    with open (filename, 'w') as fw:
FileNotFoundError: [Errno 2] No such file or directory: '/home/qianguo/EdgeScheduler/Worker/dml_file/conf/1/1_n1_dataset.conf'
222.201.187.50 - - [16/May/2025 09:33:30] "[35m[1mPOST /conf/dataset HTTP/1.1[0m" 500 -
127.0.0.1 - - [16/May/2025 09:33:35] "GET /hi HTTP/1.1" 200 -
222.201.187.50 - - [16/May/2025 09:33:38] "GET /start HTTP/1.1" 200 -
Aggregate: accuracy=0.03400000002980232, round=0,
127.0.0.1 - - [16/May/2025 09:34:05] "GET /hi HTTP/1.1" 200 -
222.201.187.50 - - [16/May/2025 09:34:27] "GET /start HTTP/1.1" 200 -
Aggregate: accuracy=0.03400000002980232, round=0,
127.0.0.1 - - [16/May/2025 09:34:35] "GET /hi HTTP/1.1" 200 -
222.201.187.50 - - [16/May/2025 09:34:38] "GET /start HTTP/1.1" 200 -
Aggregate: accuracy=0.03400000002980232, round=0,
127.0.0.1 - - [16/May/2025 09:35:05] "GET /hi HTTP/1.1" 200 -
127.0.0.1 - - [16/May/2025 09:35:35] "GET /hi HTTP/1.1" 200 -
